language: objective-c
osx_image: xcode8

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - IOS_FRAMEWORK_SCHEME="Shoyu"
    - IOS_SDK=iphonesimulator10.0
  matrix:
    - DESTINATION="OS=9.1,name=iPhone 6 Plus"   SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"    
    - DESTINATION="OS=10.0,name=iPhone 7"   SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"    

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Shoyu.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
